image: node:12

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  before_script:
    - yarn
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - packages/
      - LICENSE
      - package.json
      - README.md
      - yarn.lock

test:
  before_script:
    - yarn
  stage: build
  script:
    - yarn test
  artifacts:
    paths:
      - coverage/

lint:
  before_script:
    - yarn
    - yarn docs
  stage: build
  script:
    - yarn lint

pages:
  stage: deploy
  script:
    - mv packages/p2p-networking/docs public
    - mv packages/example public/example
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - master
